[terminal.shell]
program = "/home/vinko/.nix-profile/bin/zsh"

[window]
padding.x = 5
padding.y = 10

[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

[terminal]
